
[project]
src = "src"
out = "out"
dot_env = ".env"

[networks.contracts.price_feed]
deployer_script = "script/deploy_mocks.py"

[networks.pyevm]
is_zksync = false

[networks.sepolia]
url = "$SEPOLIA_URL"
prompt_live = false
chain_id = 11155111
save_to_db = false
default_account_name = "devkey"
explorer_uri = "https://eth-sepolia.blockscout.com/"
explorer_type = "blockscout"

[networks.op-sepolia]
url = "$OP_SEPOLIA_URL"
prompt_live = false
chain_id = 11155420
save_to_db = false
default_account_name = "devkey"
explorer_uri = 'https://optimism-sepolia.blockscout.com/'
explorer_type = 'blockscout'

[networks.sepolia.contracts.price_feed]
address = "0x1a81afB8146aeFfCFc5E50e8479e826E7D55b910"
deployer_script = "script/deploy_mocks.py"

[networks.op-sepolia.contracts.price_feed]
address = "0x828eda6b1B7266AD4d04Eb18468B965fc70940bd"
deployer_script = "script/deploy_mocks.py"

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
