[project]
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mamushi>=0.0.6",
    "moccasin>=0.4.2",
    "python-dotenv>=1.1.1",
    "titanoboa>=0.2.7",
    "web3>=7.12.1",
]
